apiVersion: batch/v1
kind: Job
metadata:
  name: checkhe-job
spec:
  template:
    spec:
      containers:
      - name: checkhe-job
        image: yash5090/checkhe:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
