apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkhe-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: checkhe
  template:
    metadata:
      labels:
        app: checkhe
    spec:
      containers:
        - name: checkhe
          image: yash5090/checkhe:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
